### PR TITLE
Move legacy library into seperate repo

### LINKED ISSUE #258: Move legacy library into seperate repo
Move the legacy libraries to joomlatools/joomla-platform-legacy

Reference : joomlatools/joomla-platform-legacy#1

### PR DESCRIPTION
**Pull request by johanjanssens**
Resolve #258

### CODE REVIEW

**Comment by johanjanssens** [comment]
@steven Can you review this ? I have put it in for the 1.1 milestone, could however also do it in 1.0.

**Comment by stevenrombauts** [comment]
@johanjanssens This works 100% on my end now too. Separate components are broken as a result of this though. I'll open up issues in the component repo's to deal with this.

I think we can add it to 1.0 release, as long as components are fixed too. It doesn't look like they need much work, it's search & replace.

**Comment by johanjanssens** [comment]
@stevenrombauts Thanks, didn't test the separate components yet. What we can do there instead of search and replace is just to require this repo as a dependency ? We can make them work without legacy later if really needed ?

**Comment by stevenrombauts** [comment]
@johanjanssens Agreed. Closing this one and will update the components to include the legacy package.

**Pull request merged**
